
package view.employees;
import dao.KhachHangDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.util.ArrayList;
import model.KhachHangModel;
import java.awt.event.*;
/**
 *
 * @author hyn09
 */
public class KhachHang extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form KhachHangJPanel
     */
    private DefaultTableModel tblModel;
    private static ArrayList<KhachHangModel> arms;
   
    public KhachHang() {
        initComponents();
        jTable1_KH.setDefaultEditor(Object.class, null);
        initTable();
        arms = KhachHangDAO.getInstance().selectAll();
        loadDataToTable(arms);
        
        btnThem.addActionListener((ActionEvent e) -> {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(KhachHang.this);
                ThemKH dialog = new ThemKH(parentFrame, true);
                dialog.setVisible(true);
        });
        btnSua.addActionListener((ActionEvent e) -> {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(KhachHang.this);
        SuaKH dialog = new SuaKH(parentFrame, true);
        dialog.setVisible(true);
    });
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã KH", "Tên khách hàng","Số điện thoại", "Email"};
        tblModel.setColumnIdentifiers(headerTbl);
        jTable1_KH.setModel(tblModel);
        jTable1_KH.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1_KH.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1_KH.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTable1_KH.getColumnModel().getColumn(3).setPreferredWidth(100);
    }

    public void loadDataToTable(ArrayList<KhachHangModel> sp) {
        try {
            tblModel.setRowCount(0);
            for (KhachHangModel i : sp) {
                tblModel.addRow(new Object[]{
                    i.getMaKH(), i.getTenKH(), i.getSdtKH(), i.getEmailKH()
                });
            }
        } catch (Exception e) {
        }
    }

    public KhachHangModel getSPSelect() {
        int i_row = jTable1_KH.getSelectedRow();
        KhachHangModel sp = KhachHangDAO.getInstance().selectAll().get(i_row);
        return sp;
    }
//    public KhachHang() {
//        initComponents();
//        initTable();
//    }
//    
//    private void initTable() {
//        Object[][] customerData = {
//        {"1", "John Doe", "john.doe@example.com", "1234567890", "123 Main St"},
//        {"2", "Jane Smith", "jane.smith@example.com", "0987654321", "456 Elm St"},
//        {"3", "Alice Johnson", "alice.johnson@example.com", "5551234567", "789 Oak St"},
//        {"4", "Bob Brown", "bob.brown@example.com", "3216549870", "101 Pine St"}
//    };
//
//    String[] customerColumnNames = {"ID", "Tên", "Email", "Số điện thoại", "Địa chỉ"};
//
//        // Tạo một đối tượng DefaultTableModel với dữ liệu và tiêu đề cột đã cho
//        DefaultTableModel model = new DefaultTableModel(customerData, customerColumnNames);
//
//        // Tạo JTable với DefaultTableModel đã tạo
//        JTable table = new JTable(model);
//
//        // Tạo JScrollPane để hiển thị JTable nếu cần
//        JScrollPane scrollPane = new JScrollPane(table);
//
//        // Thêm JScrollPane chứa JTable vào JPanel table_sanpham
//        table_khachhang.setLayout(new BorderLayout());
//        table_khachhang.add(scrollPane, BorderLayout.CENTER);
//     
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_KH = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(32, 178, 170));
        btnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");

        jButton2.setBackground(new java.awt.Color(32, 178, 170));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(32, 178, 170));
        btnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");

        jComboBox1.setBackground(new java.awt.Color(32, 178, 170));
        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khách hàng", "Tên khách hàng", "Email", "Số điện thoại", "Địa chỉ" }));

        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField6.setText("Nhập nội dung tìm kiếm...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTable1_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_KH.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1_KH.setRowHeight(30);
        jTable1_KH.setSelectionBackground(new java.awt.Color(230, 255, 255));
        jTable1_KH.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1_KH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_KH;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
